name: Update Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - descriptions/*.md
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: cuda
            short-description: NVIDIA CUDA libraries added to Rocker image.
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rocker/${{ matrix.image }}
        short-description: ${{ matrix.short-description }}
        readme-filepath: ./descriptions/${{ matrix.image }}.md
